packages:
  - "."
allowBuilds:
  esbuild: false
minimumReleaseAge: 0
shellEmulator: true
trustLockfile: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 604800
overrides:
  vite: "npm:@voidzero-dev/vite-plus-core@0.2.4"
